model_configs:
  - [2, 2, 128]    # ~0.4M params
  - [4, 4, 256]    # ~3.2M params  
  - [6, 6, 384]    # ~10M params

batch_sizes: [1, 2, 4, 8, 16, 32]
block_sizes: [64, 128, 256, 512]
devices: ['cpu', 'mps']

training:
  max_iters: 200
  eval_iters: 20
  log_interval: 1
  compile: false
  lr_decay_iters: 2000
  dropout: 0.0

output:
  results_dir: "results"
  timestamp_format: "%d%m%Y_%H%M%S"